[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "background_remover"
version = "0.1"
dependencies = [
]

[project.scripts]
background_remover = "background_remover.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]

